export const VALID_STATUSES = [
    'Active',
    'Active but Awaiting Replacement',
    'Active (Winback)',
    'Agreement Signed',
    'Appointment Held',
    'Appointment Kept',
    'Appointment Set',
    'Awaiting for OS',
    'Awaiting OS',
    'Awaiting Replacement',
    'Canceled',
    'Declined',
    'For Matching',
    'For Pairing',
    'Ghosted',
    'Hiring Fee Paid',
    'Invalid Lead',
    'Key Target Demographics',
    'Knows Cyberbacker',
    'Lead',
    'Maps Credit',
    'Matched',
    'N/A',
    'Needs Verification',
    'New Lead',
    'On Hold',
    'On Pause',
    'Paired',
    'Pending Cancelation',
    'Pending Cancellation',
    'Prime Simulations',
    'Returned SA',
    'Signed Agreement',
    'Sign Up',
    'Suspended',
    'Trade',
    'Training'
];